# Generated by Django 5.0.2 on 2024-02-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='<EMAIL>', max_length=254),
        ),
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='date',
            field=models.DateField(default='2020-05-21'),
        ),
        migrations.AlterField(
            model_name='users',
            name='fullname',
            field=models.CharField(default='francy aluma', max_length=200),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='francy aluma', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default='francy aluma', max_length=50),
        ),
    ]
