# Generated by Django 5.0.2 on 2024-02-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_users_email_alter_users_age_alter_users_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='poisson', max_length=200)),
                ('product_price', models.CharField(default='poisson', max_length=50)),
                ('product_quantity', models.IntegerField(default='<combien>')),
            ],
        ),
    ]
